[package]
name = "pybinlex"
version = "1.0.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.22.6", features = ["extension-module"] }
# crossbeam = "0.8.4"
# crossbeam-skiplist = "0.1.3"

[lib]
name = "binlex"
crate-type = ["cdylib"]

[dependencies.binlex]
path = "../../../"
